'use client';
import { useEffect, useState } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import Badge from '@/components/ui/Badge';
import { api, extractErrorMessage } from '@/lib/api';
import { formatDate } from '@/lib/utils';

interface Task {
  id: string; patientId: string; patientName: string; patientCode: string;
  village?: string; diagnosisType?: string; chwName?: string;
  triggerType: string; reason?: string; status: string; createdAt: string;
}

type BadgeVariant = 'low' | 'moderate' | 'critical';
const TRIGGER: Record<string, { label: string; variant: BadgeVariant }> = {
  MISSED_DOSES:       { label: 'Missed doses',           variant: 'moderate' },
  SIDE_EFFECT:        { label: 'Side effect',            variant: 'critical' },
  IIT_ESCALATED:      { label: 'Treatment interruption', variant: 'critical' },
  HIGH_RISK:          { label: 'High AI risk',           variant: 'critical' },
  PERIODIC_REVIEW:    { label: 'Periodic review',        variant: 'moderate' },
  INITIAL_ASSESSMENT: { label: 'Initial assessment',     variant: 'low' },
};

export default function TriggeredHomeVisitsPage() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  async function load() {
    setLoading(true);
    try {
      const r = await api.get('/api/home-visit-tasks');
      setTasks(r.data as Task[]);
      setError('');
    } catch (e) {
      setError(extractErrorMessage(e, 'Could not load triggered visits.'));
    } finally {
      setLoading(false);
    }
  }
  useEffect(() => { load(); }, []);

  async function complete(id: string) {
    try {
      await api.put(`/api/home-visit-tasks/${id}/complete`);
      setTasks((t) => t.filter((x) => x.id !== id));
    } catch (e) {
      setError(extractErrorMessage(e, 'Could not update the task.'));
    }
  }

  return (
    <DashboardLayout>
      <div className="mb-6">
        <h1 className="text-[22px] font-bold" style={{ color: 'var(--color-text-primary)' }}>
          Triggered Home Visits
        </h1>
        <p className="text-[13px] mt-1" style={{ color: 'var(--color-text-secondary)' }}>
          Patients who need an in-person visit, and why. Routine TB verification uses Video DOT —
          in-person visits are generated by clinical need, not scheduled daily.
        </p>
      </div>

      {error && <p className="text-[13px] mb-4" style={{ color: '#C0392B' }}>{error}</p>}

      {loading ? (
        <p className="text-[13px]" style={{ color: 'var(--color-text-secondary)' }}>Loading…</p>
      ) : tasks.length === 0 ? (
        <p className="text-[13px]" style={{ color: 'var(--color-text-secondary)' }}>
          No open triggered visits.
        </p>
      ) : (
        <div className="space-y-2">
          {tasks.map((t) => {
            const s = TRIGGER[t.triggerType] ?? { label: t.triggerType, variant: 'moderate' as BadgeVariant };
            return (
              <div key={t.id} className="dmc-card p-4 flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="flex items-center flex-wrap gap-2 mb-1">
                    <span className="font-semibold text-[14px]" style={{ color: 'var(--color-text-primary)' }}>
                      {t.patientName}
                    </span>
                    <span className="data-num text-[11px]" style={{ color: 'var(--color-text-hint)' }}>
                      {t.patientCode}
                    </span>
                    {t.diagnosisType && <Badge variant="low">{t.diagnosisType.replace(/_/g, ' + ')}</Badge>}
                  </div>
                  <div className="flex items-center flex-wrap gap-2 mb-1">
                    <Badge variant={s.variant}>{s.label}</Badge>
                    {t.reason && (
                      <span className="text-[12px]" style={{ color: 'var(--color-text-secondary)' }}>{t.reason}</span>
                    )}
                  </div>
                  <p className="text-[11px]" style={{ color: 'var(--color-text-hint)' }}>
                    {t.village ? `${t.village} · ` : ''}CHW: {t.chwName ?? '—'} · {formatDate(t.createdAt)}
                  </p>
                </div>
                <button
                  onClick={() => complete(t.id)}
                  className="shrink-0 text-[12px] font-semibold px-3 py-1.5 rounded-lg text-white"
                  style={{ background: 'var(--color-primary)' }}
                >
                  Mark done
                </button>
              </div>
            );
          })}
        </div>
      )}
    </DashboardLayout>
  );
}
